# Generated by Django 5.0.3 on 2026-02-09 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('SHOULDER', 'Shoulder'), ('CARDIO', 'Cardio'), ('ARMS', 'Arms'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('ABS', 'Abs'), ('MIXED', 'Mixed')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'body_part',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('max_capacity', models.IntegerField()),
                ('gym_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym',
            },
        ),
        migrations.CreateModel(
            name='GymActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('body_part', models.ForeignKey(db_column='body_part_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gym.bodypart')),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gym.gym')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='gym_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym_activity',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['gym', 'started_at'], name='gym_activit_gym_id_081cf6_idx'), models.Index(fields=['user', 'started_at'], name='gym_activit_user_id_9bab6f_idx'), models.Index(fields=['body_part', 'started_at'], name='gym_activit_body_pa_0dcbae_idx'), models.Index(fields=['gym', 'body_part', 'ended_at'], name='gym_activit_gym_id_9f0de1_idx')],
            },
        ),
        migrations.CreateModel(
            name='GymRushSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField()),
                ('rush_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rush_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, related_name='rush_snapshots', to='gym.gym')),
            ],
            options={
                'db_table': 'gym_rush_snapshot',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['gym', 'captured_at'], name='gym_rush_sn_gym_id_e79b28_idx'), models.Index(fields=['gym', 'rush_level'], name='gym_rush_sn_gym_id_bdd85d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('body_parts', models.ManyToManyField(blank=True, related_name='visits', to='gym.bodypart')),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gym.gym')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='gym_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym_visit',
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['user', 'check_in_time'], name='gym_visit_user_id_18d4f6_idx'), models.Index(fields=['gym', 'check_in_time'], name='gym_visit_gym_id_1910f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gym.gym')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='membership_user_id_dcc29c_idx'), models.Index(fields=['gym', 'is_active'], name='membership_gym_id_85a0c9_idx')],
            },
        ),
    ]
