# Generated by Django 5.0.3 on 2026-03-14 18:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('SHOULDER', 'Shoulder'), ('CARDIO', 'Cardio'), ('ARMS', 'Arms'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('ABS', 'Abs'), ('MIXED', 'Mixed')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'body_part',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic point stored as (longitude, latitude) in WGS84', null=True, srid=4326)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('max_capacity', models.IntegerField()),
                ('gym_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym',
            },
        ),
        migrations.CreateModel(
            name='GymActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('body_part', models.ForeignKey(db_column='body_part_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gym.bodypart')),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gym.gym')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='gym_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym_activity',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GymRushSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField()),
                ('rush_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rush_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, related_name='rush_snapshots', to='gym.gym')),
            ],
            options={
                'db_table': 'gym_rush_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gym.gym')),
                ('user', models.ForeignKey(db_column='user_id', help_text='Linked user account. Always present.', on_delete=django.db.models.deletion.CASCADE, related_name='gym_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, db_column='gym_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gym.gym')),
                ('member', models.ForeignKey(blank=True, db_column='member_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gym.member')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.AddConstraint(
            model_name='gym',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_gym_name'),
        ),
        migrations.AddIndex(
            model_name='gymactivity',
            index=models.Index(fields=['gym', 'started_at'], name='gym_activit_gym_id_081cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='gymactivity',
            index=models.Index(fields=['user', 'started_at'], name='gym_activit_user_id_9bab6f_idx'),
        ),
        migrations.AddIndex(
            model_name='gymactivity',
            index=models.Index(fields=['body_part', 'started_at'], name='gym_activit_body_pa_0dcbae_idx'),
        ),
        migrations.AddIndex(
            model_name='gymactivity',
            index=models.Index(fields=['gym', 'body_part', 'ended_at'], name='gym_activit_gym_id_9f0de1_idx'),
        ),
        migrations.AddIndex(
            model_name='gymrushsnapshot',
            index=models.Index(fields=['gym', 'captured_at'], name='gym_rush_sn_gym_id_e79b28_idx'),
        ),
        migrations.AddIndex(
            model_name='gymrushsnapshot',
            index=models.Index(fields=['gym', 'rush_level'], name='gym_rush_sn_gym_id_bdd85d_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'phone'], name='member_gym_id_fafcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='member_phone_c3a7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='member_user_id_72a7f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('gym', 'user'), name='unique_gym_user'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('gym', 'phone'), name='unique_gym_phone'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='membership_user_id_dcc29c_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['gym', 'is_active'], name='membership_gym_id_85a0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['member', 'is_active'], name='membership_member__e68eac_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['member', 'end_date'], name='membership_member__c02e52_idx'),
        ),
    ]
