# Generated by Django 5.0.3 on 2026-02-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymVisit',
        ),
    ]
