# Generated by Django 5.0.3 on 2026-03-06 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_delete_gymvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gym',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_gym_name'),
        ),
    ]
