# Generated by Django 5.0.3 on 2026-03-13 13:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_gym_location_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic point stored as (longitude, latitude) in WGS84', null=True, srid=4326),
        ),
    ]
